import { NextResponse } from "next/server"
import { prisma } from "@/lib/prisma"
import { ZorgorganisatieType } from "@prisma/client"

export const maxDuration = 120

interface OrgData {
  naam: string
  beschrijving?: string
  type: ZorgorganisatieType
  telefoon?: string
  email?: string
  website?: string
  gemeente: string | null
  onderdeelTest?: string
  soortHulp?: string
  dienst?: string
  doelgroep?: string
  kosten?: string
  zichtbaarBijLaag?: boolean
  zichtbaarBijGemiddeld?: boolean
  zichtbaarBijHoog?: boolean
}

async function upsertOrg(org: OrgData) {
  const existing = await prisma.zorgorganisatie.findFirst({
    where: { naam: org.naam, gemeente: org.gemeente },
  })
  if (existing) {
    await prisma.zorgorganisatie.update({
      where: { id: existing.id },
      data: {
        beschrijving: org.beschrijving, type: org.type, telefoon: org.telefoon,
        email: org.email, website: org.website, onderdeelTest: org.onderdeelTest,
        soortHulp: org.soortHulp, dienst: org.dienst, doelgroep: org.doelgroep,
        kosten: org.kosten, zichtbaarBijLaag: org.zichtbaarBijLaag ?? false,
        zichtbaarBijGemiddeld: org.zichtbaarBijGemiddeld ?? false,
        zichtbaarBijHoog: org.zichtbaarBijHoog ?? true, isActief: true,
      },
    })
    return "updated"
  } else {
    await prisma.zorgorganisatie.create({
      data: {
        naam: org.naam, beschrijving: org.beschrijving, type: org.type,
        telefoon: org.telefoon, email: org.email, website: org.website,
        gemeente: org.gemeente, onderdeelTest: org.onderdeelTest,
        soortHulp: org.soortHulp, dienst: org.dienst, doelgroep: org.doelgroep,
        kosten: org.kosten, zichtbaarBijLaag: org.zichtbaarBijLaag ?? false,
        zichtbaarBijGemiddeld: org.zichtbaarBijGemiddeld ?? false,
        zichtbaarBijHoog: org.zichtbaarBijHoog ?? true, isActief: true,
      },
    })
    return "created"
  }
}

export async function POST(request: Request) {
  let created = 0, updated = 0, errors = 0

  const allOrgs: OrgData[] = [
    // ===== NIJMEGEN =====
    { naam: "Mantelzorg Nijmegen", beschrijving: "Het eerste aanspreekpunt voor mantelzorgers. Tips, advies, steun en een luisterend oor.", type: "MANTELZORGSTEUNPUNT", telefoon: "024 254 157 12", email: "Mantelzorg@sterker.nl", website: "https://mantelzorg-nijmegen.nl", gemeente: "Nijmegen", onderdeelTest: "Mantelzorgondersteuning", soortHulp: "Informatie en advies", doelgroep: "Alle mantelzorgers", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Mantelzorg Nijmegen - Emotionele steun", beschrijving: "Luisterend oor, individuele gesprekken en emotionele ondersteuning.", type: "MANTELZORGSTEUNPUNT", telefoon: "024 254 157 12", email: "Mantelzorg@sterker.nl", website: "https://mantelzorg-nijmegen.nl/mantelzorgers/", gemeente: "Nijmegen", onderdeelTest: "Emotionele steun", soortHulp: "Emotionele steun", doelgroep: "Alle mantelzorgers", kosten: "Gratis", zichtbaarBijLaag: false, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Mantelzorg Nijmegen - Lotgenotengroepen", beschrijving: "Gespreksgroepen en wandelingen waar je andere mantelzorgers ontmoet.", type: "MANTELZORGSTEUNPUNT", telefoon: "024 254 157 12", email: "Mantelzorg@sterker.nl", website: "https://mantelzorg-nijmegen.nl/mantelzorgers/", gemeente: "Nijmegen", onderdeelTest: "Lotgenotencontact", soortHulp: "Lotgenotencontact", doelgroep: "Alle mantelzorgers", kosten: "Gratis", zichtbaarBijLaag: false, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Mantelzorg Nijmegen - Cursussen", beschrijving: "Cursussen en trainingen voor mantelzorgers.", type: "MANTELZORGSTEUNPUNT", telefoon: "024 254 157 12", email: "Mantelzorg@sterker.nl", website: "https://mantelzorg-nijmegen.nl/mantelzorgers/", gemeente: "Nijmegen", onderdeelTest: "Leren en training", soortHulp: "Educatie", doelgroep: "Alle mantelzorgers", kosten: "Gratis", zichtbaarBijLaag: false, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "ZZG Zorggroep - Mantelzorg", beschrijving: "Informatie en hulp bij mantelzorg.", type: "THUISZORG", website: "https://www.zzgzorggroep.nl/mantelzorg/", gemeente: "Nijmegen", onderdeelTest: "Mantelzorgondersteuning", soortHulp: "Informatie en advies", doelgroep: "Alle mantelzorgers", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "ZorgMies Nijmegen", beschrijving: "Hulp bij boodschappen, maaltijden, licht huishoudelijk werk en persoonlijke verzorging.", type: "THUISZORG", website: "https://zorgmies.nl/zorgmies-nijmegen/", gemeente: "Nijmegen", onderdeelTest: "Mantelzorgondersteuning", soortHulp: "Vervangende mantelzorg", doelgroep: "Mantelzorgers die ontlasting nodig hebben", zichtbaarBijLaag: false, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "VraagHulp Nijmegen", beschrijving: "Onafhankelijk informatiepunt voor mantelzorgers.", type: "GEMEENTE", website: "https://www.vraaghulpnijmegen.nl/wie-helpt/ik-ben-mantelzorger-en-heb-een-vraag/", gemeente: "Nijmegen", onderdeelTest: "Mantelzorgondersteuning", soortHulp: "Informatie en advies", doelgroep: "Alle mantelzorgers", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Gemeente Nijmegen - Mantelzorgcompliment", beschrijving: "Waardering voor mantelzorgers.", type: "GEMEENTE", website: "https://www.nijmegen.nl/diensten/zorg-en-hulp/mantelzorgcompliment/", gemeente: "Nijmegen", onderdeelTest: "Mantelzorgondersteuning", soortHulp: "Financiele regelingen", doelgroep: "Alle mantelzorgers", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Gemeente Nijmegen - Hulp huishouden mantelzorgers", beschrijving: "Tijdelijke huishoudelijke hulp voor overbelaste mantelzorgers.", type: "GEMEENTE", website: "https://www.nijmegen.nl/diensten/zorg-en-hulp/hulp-huishouden-mantelzorgers/", gemeente: "Nijmegen", onderdeelTest: "Huishoudelijke taken", soortHulp: "Praktische hulp", doelgroep: "Overbelaste mantelzorgers", zichtbaarBijLaag: false, zichtbaarBijGemiddeld: false, zichtbaarBijHoog: true },
    { naam: "Sterker Sociaal Werk Nijmegen", beschrijving: "Breed sociaal werk met ondersteuning voor mantelzorgers.", type: "SOCIAAL_WIJKTEAM", website: "https://www.sterker.nl/diensten/mantelzorg", gemeente: "Nijmegen", onderdeelTest: "Administratie en aanvragen", soortHulp: "Informatie en advies", doelgroep: "Alle inwoners", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Buurtteams Nijmegen", beschrijving: "Eerste aanspreekpunt voor hulpvragen.", type: "SOCIAAL_WIJKTEAM", website: "https://www.nijmegen.nl", gemeente: "Nijmegen", onderdeelTest: "Plannen en organiseren", soortHulp: "Informatie en advies", doelgroep: "Alle inwoners", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Hulpdienst Nijmegen - Boodschappen", beschrijving: "Vrijwilligers helpen met boodschappen doen.", type: "VRIJWILLIGERS", telefoon: "024-3228280", website: "https://www.hulpdienstnijmegen.nl/", gemeente: "Nijmegen", onderdeelTest: "Boodschappen", soortHulp: "Praktische hulp", doelgroep: "Ouderen, zieken, mantelzorgers", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "ZorgMies Nijmegen - Boodschappen", beschrijving: "Praktische hulp bij boodschappen doen.", type: "THUISZORG", website: "https://zorgmies.nl/zorgmies-nijmegen/", gemeente: "Nijmegen", onderdeelTest: "Boodschappen", soortHulp: "Praktische hulp", doelgroep: "Ouderen en zorgvragers", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Gemeente Nijmegen - Huishoudelijke hulp WMO", beschrijving: "Huishoudelijke hulp via de WMO.", type: "GEMEENTE", website: "https://www.nijmegen.nl/diensten/zorg-en-hulp/huishoudelijke-hulp/", gemeente: "Nijmegen", onderdeelTest: "Huishoudelijke taken", soortHulp: "Praktische hulp", doelgroep: "Inwoners die zelf niet kunnen schoonmaken", kosten: "\u20AC21 per maand", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Actief Zorg Nijmegen", beschrijving: "Professionele huishoudelijke hulp.", type: "THUISZORG", website: "https://www.actiefzorg.nl/thuiszorg/nijmegen/huishoudelijke-verzorging", gemeente: "Nijmegen", onderdeelTest: "Huishoudelijke taken", soortHulp: "Praktische hulp", doelgroep: "Ouderen en zorgvragers", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Uw Zorgcompaan Nijmegen", beschrijving: "Thuishulp inclusief verzorging, huishouden, boodschappen en uitjes.", type: "THUISZORG", website: "https://www.uwzorgcompaan.eu/thuishulp-nijmegen", gemeente: "Nijmegen", onderdeelTest: "Huishoudelijke taken", soortHulp: "Praktische hulp", doelgroep: "Ouderen en zorgvragers", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Hulpdienst Nijmegen - Klusjes", beschrijving: "Vrijwilligers helpen met kleine klusjes in huis.", type: "VRIJWILLIGERS", telefoon: "024-3228280", website: "https://www.hulpdienstnijmegen.nl/", gemeente: "Nijmegen", onderdeelTest: "Klusjes in en om het huis", soortHulp: "Praktische hulp", doelgroep: "Ouderen, zieken, mantelzorgers", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "AutoMaatje Nijmegen", beschrijving: "Vrijwillige chauffeurs brengen u naar afspraken.", type: "VRIJWILLIGERS", website: "https://sterkerouderenwerk.nl/en/diensten/anwb-automaatje/", gemeente: "Nijmegen", onderdeelTest: "Vervoer", soortHulp: "Praktische hulp", doelgroep: "Ouderen die niet zelf kunnen rijden", kosten: "\u20AC0,35 per km", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Regiotaxi AVAN Nijmegen", beschrijving: "Van deur tot deur vervoer.", type: "GEMEENTE", website: "https://www.avan-vervoer.nl/", gemeente: "Nijmegen", onderdeelTest: "Vervoer", soortHulp: "Praktische hulp", doelgroep: "Mensen die niet zelfstandig kunnen reizen", kosten: "Laag tarief met indicatie", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Hulpdienst Nijmegen - Vervoer", beschrijving: "Vrijwilligers bieden vervoer en begeleiding.", type: "VRIJWILLIGERS", telefoon: "024-3228280", website: "https://www.hulpdienstnijmegen.nl/", gemeente: "Nijmegen", onderdeelTest: "Vervoer", soortHulp: "Praktische hulp", doelgroep: "Ouderen, zieken, mantelzorgers", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "ZorgMies Nijmegen - Begeleid vervoer", beschrijving: "Begeleiding bij vervoer naar afspraken.", type: "THUISZORG", website: "https://zorgmies.nl/zorgmies-nijmegen/", gemeente: "Nijmegen", onderdeelTest: "Vervoer", soortHulp: "Praktische hulp", doelgroep: "Mensen die begeleiding nodig hebben", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Tafeltje Dekje Nijmegen", beschrijving: "Warme maaltijden aan huis bezorgd.", type: "VRIJWILLIGERS", website: "https://www.maaltijdvoorzieningen.nl/nijmegen/", gemeente: "Nijmegen", onderdeelTest: "Bereiden en/of nuttigen van maaltijden", soortHulp: "Praktische hulp", doelgroep: "Ouderen die niet zelf kunnen koken", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Stichting Thuisgekookt Nijmegen", beschrijving: "Buren koken voor buren. Verse maaltijden en sociaal contact.", type: "VRIJWILLIGERS", website: "https://thuisgekookt.nl/", gemeente: "Nijmegen", onderdeelTest: "Bereiden en/of nuttigen van maaltijden", soortHulp: "Praktische hulp", doelgroep: "Ouderen en mensen die behoefte hebben aan contact", kosten: "Laag tarief", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Hulpdienst Nijmegen - Bezoek", beschrijving: "Vrijwilligers komen langs voor gezelschap.", type: "VRIJWILLIGERS", telefoon: "024-3228280", website: "https://www.hulpdienstnijmegen.nl/", gemeente: "Nijmegen", onderdeelTest: "Sociaal contact en activiteiten", soortHulp: "Praktische hulp", doelgroep: "Ouderen, zieken, eenzame mensen", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Maatjes Nijmegen", beschrijving: "Vrijwillige maatjes voor sociaal contact.", type: "VRIJWILLIGERS", website: "https://www.maatjesnijmegen.nl/", gemeente: "Nijmegen", onderdeelTest: "Sociaal contact en activiteiten", soortHulp: "Praktische hulp", doelgroep: "Mensen die behoefte hebben aan sociaal contact", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Hulpdienst Nijmegen - Administratie", beschrijving: "Vrijwilligers helpen met eenvoudige administratieve taken.", type: "VRIJWILLIGERS", telefoon: "024-3228280", website: "https://www.hulpdienstnijmegen.nl/", gemeente: "Nijmegen", onderdeelTest: "Administratie en aanvragen", soortHulp: "Praktische hulp", doelgroep: "Ouderen, zieken, mantelzorgers", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "ZZG Zorggroep Nijmegen - Thuiszorg", beschrijving: "Professionele thuiszorg: persoonlijke verzorging, verpleging en begeleiding.", type: "THUISZORG", website: "https://www.zzgzorggroep.nl/zorg-thuis/", gemeente: "Nijmegen", onderdeelTest: "Persoonlijke verzorging", soortHulp: "Professionele zorg", doelgroep: "Mensen met zorgbehoefte", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Sterker Ouderenwerk - Deel de Dag", beschrijving: "Dagbesteding voor senioren. Gratis voor Nijmegse 65-plussers.", type: "DAGBESTEDING", website: "https://sterkerouderenwerk.nl/en/diensten/deel-de-dag-dagbesteding/", gemeente: "Nijmegen", onderdeelTest: "Vervangende mantelzorg", soortHulp: "Vervangende mantelzorg", doelgroep: "Senioren 65+ in Nijmegen", kosten: "Gratis (subsidie gemeente)", zichtbaarBijLaag: false, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "OBG Dagbesteding Nijmegen", beschrijving: "Dagbesteding voor mensen met lichte tot zwaardere zorgvraag.", type: "DAGBESTEDING", website: "https://obg.nu/zorg-gezondheid/dagbesteding/", gemeente: "Nijmegen", onderdeelTest: "Vervangende mantelzorg", soortHulp: "Vervangende mantelzorg", doelgroep: "Mensen met zorgvraag", zichtbaarBijLaag: false, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "ZZG Zorggroep - Dagbehandeling", beschrijving: "Dagbehandeling op locatie Maanvis in Hatert.", type: "DAGBESTEDING", website: "https://www.zzgzorggroep.nl/zorg-thuis/dagbehandeling-op-locatie/", gemeente: "Nijmegen", onderdeelTest: "Vervangende mantelzorg", soortHulp: "Vervangende mantelzorg", doelgroep: "Mensen met zorgvraag", zichtbaarBijLaag: false, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Sterker Sociaal Werk - Clientondersteuning", beschrijving: "Hulp bij het regelen van zorg. Onafhankelijke clientondersteuning.", type: "SOCIAAL_WIJKTEAM", website: "https://www.sterker.nl/", gemeente: "Nijmegen", onderdeelTest: "Plannen en organiseren", soortHulp: "Informatie en advies", doelgroep: "Alle inwoners", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "MEE Gelderse Poort Nijmegen", beschrijving: "Onafhankelijke clientondersteuning.", type: "OVERIG", website: "https://www.meegeldersepoort.nl/", gemeente: "Nijmegen", onderdeelTest: "Plannen en organiseren", soortHulp: "Informatie en advies", doelgroep: "Mensen met een beperking of chronische ziekte", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Dierenambulance Nijmegen", beschrijving: "Hulp bij vervoer van zieke of gewonde huisdieren.", type: "VRIJWILLIGERS", telefoon: "024-3731594", website: "https://www.dierenambulancenijmegen.nl/", gemeente: "Nijmegen", onderdeelTest: "Huisdieren", soortHulp: "Praktische hulp", doelgroep: "Huisdiereigenaren", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Dierenvoedselbank Nijmegen", beschrijving: "Gratis dierenvoer voor mensen met een laag inkomen.", type: "VRIJWILLIGERS", website: "https://www.dierenvoedselbanknederland.nl/", gemeente: "Nijmegen", onderdeelTest: "Huisdieren", soortHulp: "Praktische hulp", doelgroep: "Huisdiereigenaren met laag inkomen", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Hulpdienst Nijmegen - Huisdieren uitlaten", beschrijving: "Vrijwilligers helpen met het uitlaten van de hond.", type: "VRIJWILLIGERS", telefoon: "024-3228280", website: "https://www.hulpdienstnijmegen.nl/", gemeente: "Nijmegen", onderdeelTest: "Huisdieren", soortHulp: "Praktische hulp", doelgroep: "Ouderen, zieken, mantelzorgers", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },

    // ===== ARNHEM =====
    { naam: "MVT Arnhem - Mantelzorg en Vrijwillige Thuishulp", beschrijving: "Ondersteuning voor alle mantelzorgers in Arnhem.", type: "MANTELZORGSTEUNPUNT", website: "https://www.mvtarnhem.nl/", gemeente: "Arnhem", onderdeelTest: "Mantelzorgondersteuning", soortHulp: "Informatie en advies", doelgroep: "Alle mantelzorgers in Arnhem", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "MVT Arnhem - Emotionele ondersteuning", beschrijving: "Luisterend oor en individuele gesprekken.", type: "MANTELZORGSTEUNPUNT", website: "https://www.mvtarnhem.nl/", gemeente: "Arnhem", onderdeelTest: "Emotionele steun", soortHulp: "Emotionele steun", doelgroep: "Alle mantelzorgers", kosten: "Gratis", zichtbaarBijLaag: false, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "MVT Arnhem - Lotgenotengroepen", beschrijving: "Gespreksgroepen en activiteiten met andere mantelzorgers.", type: "MANTELZORGSTEUNPUNT", website: "https://www.mvtarnhem.nl/", gemeente: "Arnhem", onderdeelTest: "Lotgenotencontact", soortHulp: "Lotgenotencontact", doelgroep: "Alle mantelzorgers", kosten: "Gratis", zichtbaarBijLaag: false, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "MVT Arnhem - Training en voorlichting", beschrijving: "Trainingen en workshops voor mantelzorgers.", type: "MANTELZORGSTEUNPUNT", website: "https://www.mvtarnhem.nl/", gemeente: "Arnhem", onderdeelTest: "Leren en training", soortHulp: "Educatie", doelgroep: "Alle mantelzorgers", kosten: "Gratis", zichtbaarBijLaag: false, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "MVT Arnhem - Jonge mantelzorgers", beschrijving: "Speciale ondersteuning voor jongeren die zorgen voor een naaste.", type: "MANTELZORGSTEUNPUNT", website: "https://www.mvtarnhem.nl/", gemeente: "Arnhem", onderdeelTest: "Mantelzorgondersteuning", soortHulp: "Emotionele steun", doelgroep: "Jonge mantelzorgers tot 24 jaar", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "MVT Arnhem - Werkende mantelzorgers", beschrijving: "Ondersteuning voor mantelzorgers die werk en zorg combineren.", type: "MANTELZORGSTEUNPUNT", website: "https://www.mvtarnhem.nl/", gemeente: "Arnhem", onderdeelTest: "Mantelzorgondersteuning", soortHulp: "Informatie en advies", doelgroep: "Werkende mantelzorgers", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "MVT Arnhem - Mantelzorg & Andere cultuur", beschrijving: "Ondersteuning voor mantelzorgers met een migratie-achtergrond.", type: "MANTELZORGSTEUNPUNT", website: "https://www.mvtarnhem.nl/mantelzorg-en-cultuur", gemeente: "Arnhem", onderdeelTest: "Mantelzorgondersteuning", soortHulp: "Emotionele steun", doelgroep: "Mantelzorgers met migratie-achtergrond", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "MVT Arnhem - Dementie mantelzorgers", beschrijving: "Speciale ondersteuning voor mantelzorgers van mensen met dementie.", type: "MANTELZORGSTEUNPUNT", website: "https://www.mvtarnhem.nl/", gemeente: "Arnhem", onderdeelTest: "Emotionele steun", soortHulp: "Emotionele steun", doelgroep: "Mantelzorgers van mensen met dementie", kosten: "Gratis", zichtbaarBijLaag: false, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Gemeente Arnhem - Mantelzorgcompliment", beschrijving: "Waardering voor mantelzorgers via het mantelzorgcompliment.", type: "GEMEENTE", website: "https://www.mvtarnhem.nl/mantelzorgcompliment", gemeente: "Arnhem", onderdeelTest: "Mantelzorgondersteuning", soortHulp: "Financiele regelingen", doelgroep: "Alle mantelzorgers in Arnhem", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Adviespunt Zorgbelang Arnhem", beschrijving: "Gratis onafhankelijke clientondersteuning.", type: "OVERIG", website: "https://www.mvtarnhem.nl/organisaties-in-arnhem/onafhankelijke-client-ondersteuning", gemeente: "Arnhem", onderdeelTest: "Mantelzorgondersteuning", soortHulp: "Informatie en advies", doelgroep: "Alle inwoners van Arnhem", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Sociale Wijkteams Arnhem", beschrijving: "Eerste aanspreekpunt voor hulp in de wijk.", type: "SOCIAAL_WIJKTEAM", website: "https://www.arnhem.nl/alle-onderwerpen/zorg-en-welzijn/mantelzorgers-en-vrijwilligers/", gemeente: "Arnhem", onderdeelTest: "Plannen en organiseren", soortHulp: "Informatie en advies", doelgroep: "Alle inwoners", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "MVT Arnhem - Vrijwillige Thuishulp", beschrijving: "Vrijwilligers helpen met tuinonderhoud en klusjes.", type: "VRIJWILLIGERS", website: "https://www.mvtarnhem.nl/", gemeente: "Arnhem", onderdeelTest: "Klusjes in en om het huis", soortHulp: "Praktische hulp", doelgroep: "Mantelzorgers en zorgvragers", kosten: "Gratis", zichtbaarBijLaag: false, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Bijzonder in Arnhem - Mantelzorg", beschrijving: "Overzicht van alle mantelzorg ondersteuning in Arnhem.", type: "OVERIG", website: "https://www.bijzonderinarnhem.nl/mantelzorg", gemeente: "Arnhem", onderdeelTest: "Mantelzorgondersteuning", soortHulp: "Informatie en advies", doelgroep: "Alle mantelzorgers", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Arnhem Doet - Mantelzorg platform", beschrijving: "Platform met informatie over mantelzorg ondersteuning.", type: "OVERIG", website: "https://arnhemdoet.nl/thema-s/mantelzorg/", gemeente: "Arnhem", onderdeelTest: "Mantelzorgondersteuning", soortHulp: "Informatie en advies", doelgroep: "Alle mantelzorgers", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "MVT Arnhem - Boodschappen hulp", beschrijving: "Vrijwilligers helpen met boodschappen doen.", type: "VRIJWILLIGERS", telefoon: "026-3703540", website: "https://www.mvtarnhem.nl/thuishulp", gemeente: "Arnhem", onderdeelTest: "Boodschappen", soortHulp: "Praktische hulp", doelgroep: "Ouderen, zieken, mantelzorgers", kosten: "\u20AC5 per klus", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "ZorgMies Arnhem - Boodschappen", beschrijving: "Praktische hulp bij boodschappen.", type: "THUISZORG", website: "https://zorgmies.nl/zorgmies-arnhem/", gemeente: "Arnhem", onderdeelTest: "Boodschappen", soortHulp: "Praktische hulp", doelgroep: "Ouderen en zorgvragers", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "VoorElkaarInArnhem - Boodschappen", beschrijving: "Hulp bij boodschappen doen.", type: "VRIJWILLIGERS", website: "https://www.voorelkaarinarnhem.nl/", gemeente: "Arnhem", onderdeelTest: "Boodschappen", soortHulp: "Praktische hulp", doelgroep: "Inwoners die hulp nodig hebben", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Pleyade Arnhem - Huishoudelijke hulp", beschrijving: "Professionele huishoudelijke hulp via WMO.", type: "THUISZORG", website: "https://pleyade.nl/zorg/thuis/6/huishoudelijke-hulp", gemeente: "Arnhem", onderdeelTest: "Huishoudelijke taken", soortHulp: "Praktische hulp", doelgroep: "Ouderen rond Pleyade locaties", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Actief Zorg Arnhem", beschrijving: "Huishoudelijke hulp via WMO of particulier.", type: "THUISZORG", website: "https://www.actiefzorg.nl/thuiszorg/arnhem/huishoudelijke-verzorging", gemeente: "Arnhem", onderdeelTest: "Huishoudelijke taken", soortHulp: "Praktische hulp", doelgroep: "Ouderen en zorgvragers", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "VoorElkaarInArnhem - Huishouden", beschrijving: "Hulp bij schoonmaken en opruimen.", type: "VRIJWILLIGERS", website: "https://www.voorelkaarinarnhem.nl/", gemeente: "Arnhem", onderdeelTest: "Huishoudelijke taken", soortHulp: "Praktische hulp", doelgroep: "Inwoners die hulp nodig hebben", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "MVT Arnhem - Kleine klusjes", beschrijving: "Vrijwilligers helpen met kleine klusjes.", type: "VRIJWILLIGERS", telefoon: "026-3703540", website: "https://www.mvtarnhem.nl/thuishulp", gemeente: "Arnhem", onderdeelTest: "Klusjes in en om het huis", soortHulp: "Praktische hulp", doelgroep: "Ouderen, zieken, mantelzorgers", kosten: "\u20AC5 per klus", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "MVT Arnhem - Tuinwerk", beschrijving: "Vrijwilligers helpen met tuinonderhoud.", type: "VRIJWILLIGERS", telefoon: "026-3703540", website: "https://www.mvtarnhem.nl/thuishulp", gemeente: "Arnhem", onderdeelTest: "Klusjes in en om het huis", soortHulp: "Praktische hulp", doelgroep: "Ouderen, zieken, mantelzorgers", kosten: "\u20AC5 per klus", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "VoorElkaarInArnhem - Klusjes", beschrijving: "Hulp bij kleine klusjes.", type: "VRIJWILLIGERS", website: "https://www.voorelkaarinarnhem.nl/", gemeente: "Arnhem", onderdeelTest: "Klusjes in en om het huis", soortHulp: "Praktische hulp", doelgroep: "Inwoners die hulp nodig hebben", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Regiotaxi AVAN Arnhem", beschrijving: "Van deur tot deur vervoer.", type: "GEMEENTE", website: "https://www.avan-vervoer.nl/", gemeente: "Arnhem", onderdeelTest: "Vervoer", soortHulp: "Praktische hulp", doelgroep: "Mensen die niet zelfstandig kunnen reizen", kosten: "Laag tarief met indicatie", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "AutoMaatje Arnhem", beschrijving: "Vrijwillige chauffeurs brengen ouderen naar afspraken.", type: "VRIJWILLIGERS", website: "https://arnhemdoet.nl/hulp-en-ondersteuning/", gemeente: "Arnhem", onderdeelTest: "Vervoer", soortHulp: "Praktische hulp", doelgroep: "Ouderen die niet zelf kunnen rijden", kosten: "\u20AC0,35 per km", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "SWOA PlusBus Arnhem", beschrijving: "Vervoer naar activiteiten en uitjes voor ouderen.", type: "VRIJWILLIGERS", website: "https://arnhemdoet.nl/hulp-en-ondersteuning/", gemeente: "Arnhem", onderdeelTest: "Vervoer", soortHulp: "Praktische hulp", doelgroep: "Ouderen 55+", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "ZorgMies Arnhem - Begeleid vervoer", beschrijving: "Begeleiding bij vervoer naar afspraken.", type: "THUISZORG", website: "https://zorgmies.nl/zorgmies-arnhem/", gemeente: "Arnhem", onderdeelTest: "Vervoer", soortHulp: "Praktische hulp", doelgroep: "Mensen die begeleiding nodig hebben", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Maaltijdservice Arnhem", beschrijving: "Warme maaltijden aan huis bezorgd.", type: "OVERIG", website: "https://www.maaltijdvoorzieningen.nl/arnhem/", gemeente: "Arnhem", onderdeelTest: "Bereiden en/of nuttigen van maaltijden", soortHulp: "Praktische hulp", doelgroep: "Ouderen die niet zelf kunnen koken", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "VoorElkaarInArnhem - Maaltijden", beschrijving: "Hulp bij maaltijd bereiden.", type: "VRIJWILLIGERS", website: "https://www.voorelkaarinarnhem.nl/", gemeente: "Arnhem", onderdeelTest: "Bereiden en/of nuttigen van maaltijden", soortHulp: "Praktische hulp", doelgroep: "Inwoners die hulp nodig hebben", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "ZorgMies Arnhem - Maaltijden", beschrijving: "Hulp bij maaltijden bereiden en gezelschap tijdens eten.", type: "THUISZORG", website: "https://zorgmies.nl/zorgmies-arnhem/", gemeente: "Arnhem", onderdeelTest: "Bereiden en/of nuttigen van maaltijden", soortHulp: "Praktische hulp", doelgroep: "Ouderen en zorgvragers", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Suz&So Arnhem", beschrijving: "Activiteitencentrum met dagbesteding.", type: "DAGBESTEDING", website: "https://suzenso.nl/", gemeente: "Arnhem", onderdeelTest: "Sociaal contact en activiteiten", soortHulp: "Praktische hulp", doelgroep: "Kwetsbare burgers, ouderen", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "SWOA Arnhem - Activiteiten", beschrijving: "Activiteiten en ondersteuning voor 55-plussers.", type: "VRIJWILLIGERS", website: "https://arnhemdoet.nl/hulp-en-ondersteuning/", gemeente: "Arnhem", onderdeelTest: "Sociaal contact en activiteiten", soortHulp: "Praktische hulp", doelgroep: "Ouderen 55+", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "MVT Arnhem - Computerhulp", beschrijving: "Vrijwilligers helpen met computer en software.", type: "VRIJWILLIGERS", telefoon: "026-3703540", website: "https://www.mvtarnhem.nl/thuishulp", gemeente: "Arnhem", onderdeelTest: "Administratie en aanvragen", soortHulp: "Praktische hulp", doelgroep: "Ouderen, zieken, mantelzorgers", kosten: "\u20AC5 per klus", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "ZorgMies Arnhem - Persoonlijke verzorging", beschrijving: "Hulp bij persoonlijke verzorging.", type: "THUISZORG", website: "https://zorgmies.nl/zorgmies-arnhem/", gemeente: "Arnhem", onderdeelTest: "Persoonlijke verzorging", soortHulp: "Professionele zorg", doelgroep: "Ouderen en zorgvragers", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "DrieGasthuizenGroep - De Bonte Specht", beschrijving: "Dagbesteding voor ouderen met beginnende dementie.", type: "DAGBESTEDING", website: "https://www.driegasthuizengroep.nl/zorg/dagbesteding/", gemeente: "Arnhem", onderdeelTest: "Vervangende mantelzorg", soortHulp: "Vervangende mantelzorg", doelgroep: "Ouderen met beginnende dementie", zichtbaarBijLaag: false, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Insula Dei Huize Kohlmann - Logeeropvang", beschrijving: "Vervangende mantelzorg in de vorm van logeren.", type: "RESPIJTZORG", website: "https://www.insuladei.nl/zorg/tijdelijk-verblijf-en-logeren/", gemeente: "Arnhem", onderdeelTest: "Vervangende mantelzorg", soortHulp: "Vervangende mantelzorg", doelgroep: "Mensen met WLZ-indicatie, mantelzorgers", kosten: "Via WLZ of WMO", zichtbaarBijLaag: false, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Derman Zorg Arnhem - Dagbesteding", beschrijving: "Dagbesteding en woonzorg.", type: "DAGBESTEDING", website: "https://dermanzorg.com/zorgaanbod/", gemeente: "Arnhem", onderdeelTest: "Vervangende mantelzorg", soortHulp: "Vervangende mantelzorg", doelgroep: "Mensen met dementie, ziekte of ouderdom", zichtbaarBijLaag: false, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Netwerk Dementie Arnhem - Vervangende mantelzorg", beschrijving: "Informatie over vervangende mantelzorg: dagopvang, logeeropvang en begeleiding.", type: "OVERIG", website: "https://www.netwerkdementiearnhemeo.nl/aanbod-per-gemeente/gemeente-arnhem/", gemeente: "Arnhem", onderdeelTest: "Vervangende mantelzorg", soortHulp: "Vervangende mantelzorg", doelgroep: "Mantelzorgers van mensen met dementie", kosten: "Via WMO, WLZ of zorgverzekeraar", zichtbaarBijLaag: false, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Wijkteams Arnhem - Clientondersteuning", beschrijving: "Hulp bij het regelen van zorg.", type: "SOCIAAL_WIJKTEAM", website: "https://www.wijkteamsarnhem.nl/", gemeente: "Arnhem", onderdeelTest: "Plannen en organiseren", soortHulp: "Informatie en advies", doelgroep: "Alle inwoners", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "MEE Gelderse Poort Arnhem", beschrijving: "Onafhankelijke clientondersteuning.", type: "OVERIG", website: "https://www.meegeldersepoort.nl/", gemeente: "Arnhem", onderdeelTest: "Plannen en organiseren", soortHulp: "Informatie en advies", doelgroep: "Mensen met een beperking of chronische ziekte", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Dierenambulance Arnhem", beschrijving: "Hulp bij vervoer van zieke of gewonde huisdieren.", type: "VRIJWILLIGERS", telefoon: "0900-0245", website: "https://www.dierenambulance-arnhem.nl/", gemeente: "Arnhem", onderdeelTest: "Huisdieren", soortHulp: "Praktische hulp", doelgroep: "Huisdiereigenaren", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Dierenvoedselbank Arnhem", beschrijving: "Gratis dierenvoer voor mensen met een laag inkomen.", type: "VRIJWILLIGERS", website: "https://www.dierenvoedselbanknederland.nl/", gemeente: "Arnhem", onderdeelTest: "Huisdieren", soortHulp: "Praktische hulp", doelgroep: "Huisdiereigenaren met laag inkomen", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Dierenasiel Arnhem", beschrijving: "Tijdelijke opvang voor huisdieren.", type: "VRIJWILLIGERS", telefoon: "026-4421471", website: "https://www.dierenasielarnhem.nl/", gemeente: "Arnhem", onderdeelTest: "Huisdieren", soortHulp: "Praktische hulp", doelgroep: "Huisdiereigenaren", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },

    // ===== ZUTPHEN =====
    { naam: "Perspectief Zutphen - Mantelzorgondersteuning", beschrijving: "Het aanspreekpunt voor mantelzorgers in Zutphen. Advies, informatie en een luisterend oor.", type: "MANTELZORGSTEUNPUNT", telefoon: "0575-519700", website: "https://www.perspectief.nu/", gemeente: "Zutphen", onderdeelTest: "Mantelzorgondersteuning", soortHulp: "Informatie en advies", doelgroep: "Alle mantelzorgers", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Perspectief Zutphen - Emotionele steun", beschrijving: "Luisterend oor, individuele gesprekken en emotionele ondersteuning voor mantelzorgers.", type: "MANTELZORGSTEUNPUNT", telefoon: "0575-519700", website: "https://www.perspectief.nu/", gemeente: "Zutphen", onderdeelTest: "Emotionele steun", soortHulp: "Emotionele steun", doelgroep: "Alle mantelzorgers", kosten: "Gratis", zichtbaarBijLaag: false, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Perspectief Zutphen - Lotgenotengroepen", beschrijving: "Gespreksgroepen waar je andere mantelzorgers ontmoet en ervaringen deelt.", type: "MANTELZORGSTEUNPUNT", telefoon: "0575-519700", website: "https://www.perspectief.nu/", gemeente: "Zutphen", onderdeelTest: "Lotgenotencontact", soortHulp: "Lotgenotencontact", doelgroep: "Alle mantelzorgers", kosten: "Gratis", zichtbaarBijLaag: false, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Perspectief Zutphen - Cursussen en training", beschrijving: "Cursussen en trainingen voor mantelzorgers, zoals omgaan met stress en grenzen stellen.", type: "MANTELZORGSTEUNPUNT", telefoon: "0575-519700", website: "https://www.perspectief.nu/", gemeente: "Zutphen", onderdeelTest: "Leren en training", soortHulp: "Educatie", doelgroep: "Alle mantelzorgers", kosten: "Gratis", zichtbaarBijLaag: false, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Gemeente Zutphen - Mantelzorgcompliment", beschrijving: "Jaarlijkse waardering van de gemeente voor mantelzorgers. Aanvragen via het Sociaal Wijkteam.", type: "GEMEENTE", website: "https://www.zutphen.nl/", gemeente: "Zutphen", onderdeelTest: "Mantelzorgondersteuning", soortHulp: "Financiele regelingen", doelgroep: "Alle mantelzorgers in Zutphen", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Sociaal Wijkteam Zutphen", beschrijving: "Eerste aanspreekpunt voor vragen over zorg, welzijn en ondersteuning.", type: "SOCIAAL_WIJKTEAM", website: "https://www.zutphen.nl/", gemeente: "Zutphen", onderdeelTest: "Plannen en organiseren", soortHulp: "Informatie en advies", doelgroep: "Alle inwoners", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Perspectief Zutphen - Boodschappenhulp", beschrijving: "Vrijwilligers helpen met boodschappen doen.", type: "VRIJWILLIGERS", telefoon: "0575-519700", website: "https://www.perspectief.nu/", gemeente: "Zutphen", onderdeelTest: "Boodschappen", soortHulp: "Praktische hulp", doelgroep: "Ouderen, zieken, mantelzorgers", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Gemeente Zutphen - Huishoudelijke hulp WMO", beschrijving: "Huishoudelijke hulp via de WMO. Aanvragen via het Sociaal Wijkteam.", type: "GEMEENTE", website: "https://www.zutphen.nl/", gemeente: "Zutphen", onderdeelTest: "Huishoudelijke taken", soortHulp: "Praktische hulp", doelgroep: "Inwoners die zelf niet kunnen schoonmaken", kosten: "Eigen bijdrage via CAK", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Perspectief Zutphen - Klusjes", beschrijving: "Vrijwilligers helpen met kleine klusjes in en om het huis.", type: "VRIJWILLIGERS", telefoon: "0575-519700", website: "https://www.perspectief.nu/", gemeente: "Zutphen", onderdeelTest: "Klusjes in en om het huis", soortHulp: "Praktische hulp", doelgroep: "Ouderen, zieken, mantelzorgers", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "AutoMaatje Zutphen", beschrijving: "Vrijwillige chauffeurs brengen u naar afspraken.", type: "VRIJWILLIGERS", website: "https://www.anwb.nl/automaatje", gemeente: "Zutphen", onderdeelTest: "Vervoer", soortHulp: "Praktische hulp", doelgroep: "Ouderen die niet zelf kunnen rijden", kosten: "\u20AC0,35 per km", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Regiotaxi Zutphen", beschrijving: "Van deur tot deur vervoer voor mensen die niet zelfstandig kunnen reizen.", type: "GEMEENTE", website: "https://www.zutphen.nl/", gemeente: "Zutphen", onderdeelTest: "Vervoer", soortHulp: "Praktische hulp", doelgroep: "Mensen die niet zelfstandig kunnen reizen", kosten: "Laag tarief met indicatie", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Tafeltje Dekje Zutphen", beschrijving: "Warme maaltijden aan huis bezorgd.", type: "VRIJWILLIGERS", website: "https://www.maaltijdvoorzieningen.nl/", gemeente: "Zutphen", onderdeelTest: "Bereiden en/of nuttigen van maaltijden", soortHulp: "Praktische hulp", doelgroep: "Ouderen die niet zelf kunnen koken", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Perspectief Zutphen - Maatjes", beschrijving: "Vrijwillige maatjes voor sociaal contact en activiteiten.", type: "VRIJWILLIGERS", telefoon: "0575-519700", website: "https://www.perspectief.nu/", gemeente: "Zutphen", onderdeelTest: "Sociaal contact en activiteiten", soortHulp: "Praktische hulp", doelgroep: "Mensen die behoefte hebben aan sociaal contact", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Perspectief Zutphen - Administratiehulp", beschrijving: "Vrijwilligers helpen met eenvoudige administratieve taken.", type: "VRIJWILLIGERS", telefoon: "0575-519700", website: "https://www.perspectief.nu/", gemeente: "Zutphen", onderdeelTest: "Administratie en aanvragen", soortHulp: "Praktische hulp", doelgroep: "Ouderen, zieken, mantelzorgers", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "ZZG Zorggroep Zutphen - Thuiszorg", beschrijving: "Professionele thuiszorg: persoonlijke verzorging, verpleging en begeleiding.", type: "THUISZORG", website: "https://www.zzgzorggroep.nl/zorg-thuis/", gemeente: "Zutphen", onderdeelTest: "Persoonlijke verzorging", soortHulp: "Professionele zorg", doelgroep: "Mensen met zorgbehoefte", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Dagbesteding De Hanzehof Zutphen", beschrijving: "Dagbesteding en activiteiten voor ouderen en mensen met dementie.", type: "DAGBESTEDING", website: "https://www.zutphen.nl/", gemeente: "Zutphen", onderdeelTest: "Vervangende mantelzorg", soortHulp: "Vervangende mantelzorg", doelgroep: "Ouderen en mensen met dementie", zichtbaarBijLaag: false, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "MEE Veluwe Zutphen", beschrijving: "Onafhankelijke clientondersteuning voor mensen met een beperking.", type: "OVERIG", website: "https://www.mee.nl/", gemeente: "Zutphen", onderdeelTest: "Plannen en organiseren", soortHulp: "Informatie en advies", doelgroep: "Mensen met een beperking of chronische ziekte", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Dierenvoedselbank Zutphen", beschrijving: "Gratis dierenvoer voor mensen met een laag inkomen.", type: "VRIJWILLIGERS", website: "https://www.dierenvoedselbanknederland.nl/", gemeente: "Zutphen", onderdeelTest: "Huisdieren", soortHulp: "Praktische hulp", doelgroep: "Huisdiereigenaren met laag inkomen", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },

    // ===== LANDELIJK =====
    { naam: "Mantelzorglijn", beschrijving: "Gratis hulplijn voor alle vragen over mantelzorg.", type: "LANDELIJK", telefoon: "030 760 60 55", website: "https://www.mantelzorg.nl/onderwerpen/ondersteuning/waar-kun-je-terecht/mantelzorglijn", gemeente: null, onderdeelTest: "Mantelzorgondersteuning", soortHulp: "Hulplijn", doelgroep: "Alle mantelzorgers", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Luisterlijn", beschrijving: "Anoniem praten over wat je dwars zit. 24/7 bereikbaar.", type: "LANDELIJK", telefoon: "0900 0767", website: "https://www.deluisterlijn.nl/", gemeente: null, onderdeelTest: "Emotionele steun", soortHulp: "Hulplijn", doelgroep: "Iedereen", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Alzheimer Telefoon", beschrijving: "Vragen over dementie? Bel voor informatie en advies.", type: "LANDELIJK", telefoon: "0800 5088", website: "https://www.alzheimer-nederland.nl/", gemeente: null, onderdeelTest: "Mantelzorgondersteuning", soortHulp: "Hulplijn", doelgroep: "Mantelzorgers van mensen met dementie", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Zilverlijn", beschrijving: "Bel voor een praatje als je je alleen voelt.", type: "LANDELIJK", telefoon: "0900 265 65 65", website: "https://www.ouderenfonds.nl/zilverlijn/", gemeente: null, onderdeelTest: "Sociaal contact en activiteiten", soortHulp: "Hulplijn", doelgroep: "Ouderen die eenzaam zijn", kosten: "Lokaal tarief", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Sensoor - Telefonische hulpdienst", beschrijving: "Dag en nacht bereikbaar voor een vertrouwelijk gesprek.", type: "LANDELIJK", telefoon: "0900 0101", website: "https://www.sensoor.nl/", gemeente: null, onderdeelTest: "Emotionele steun", soortHulp: "Hulplijn", doelgroep: "Iedereen", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Regelhulp.nl", beschrijving: "Overzicht van hulp en ondersteuning bij ziekte, handicap of ouderdom.", type: "LANDELIJK", website: "https://www.regelhulp.nl/", gemeente: null, onderdeelTest: "Administratie en aanvragen", soortHulp: "Overheid en financieel", doelgroep: "Zorgvragers en mantelzorgers", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Het CAK", beschrijving: "Informatie over eigen bijdrage voor Wmo en Wlz.", type: "LANDELIJK", telefoon: "0800 1925", website: "https://www.hetcak.nl/", gemeente: null, onderdeelTest: "Administratie en aanvragen", soortHulp: "Overheid en financieel", doelgroep: "Mensen met Wmo of Wlz-zorg", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "SVB (Sociale Verzekeringsbank)", beschrijving: "Beheert het persoonsgebonden budget (PGB).", type: "LANDELIJK", telefoon: "030 264 82 00", website: "https://www.svb.nl/nl/pgb", gemeente: null, onderdeelTest: "Administratie en aanvragen", soortHulp: "Overheid en financieel", doelgroep: "PGB-houders", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Zorginstituut Nederland", beschrijving: "Wat zit er in het basispakket van de zorgverzekering?", type: "LANDELIJK", website: "https://www.zorginstituutnederland.nl/", gemeente: null, onderdeelTest: "Administratie en aanvragen", soortHulp: "Overheid en financieel", doelgroep: "Zorgvragers en mantelzorgers", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "MantelzorgNL", beschrijving: "De landelijke vereniging voor mantelzorgers.", type: "LANDELIJK", website: "https://www.mantelzorg.nl/", gemeente: null, onderdeelTest: "Mantelzorgondersteuning", soortHulp: "Belangenorganisatie", doelgroep: "Alle mantelzorgers", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Mezzo - Landelijke vereniging mantelzorgers", beschrijving: "Informatie en belangenbehartiging voor mantelzorgers.", type: "LANDELIJK", website: "https://www.mezzo.nl/", gemeente: null, onderdeelTest: "Mantelzorgondersteuning", soortHulp: "Belangenorganisatie", doelgroep: "Mantelzorgers en vrijwilligers", kosten: "Gratis", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
    { naam: "Per Saldo - PGB-belangenvereniging", beschrijving: "Alles over het persoonsgebonden budget.", type: "LANDELIJK", telefoon: "030 230 05 45", website: "https://www.pgb.nl/", gemeente: null, onderdeelTest: "Administratie en aanvragen", soortHulp: "Belangenorganisatie", doelgroep: "PGB-houders en mantelzorgers", kosten: "Gratis voor leden", zichtbaarBijLaag: true, zichtbaarBijGemiddeld: true, zichtbaarBijHoog: true },
  ]

  for (const org of allOrgs) {
    try {
      const result = await upsertOrg(org)
      if (result === "created") created++
      else updated++
    } catch (e) {
      console.error(`Error: ${org.naam}`, e)
      errors++
    }
  }

  return NextResponse.json({
    success: true,
    totaal: allOrgs.length,
    nieuw: created,
    bijgewerkt: updated,
    fouten: errors,
  })
}
