/**
 * Seed script voor zorgorganisaties in Nijmegen en Arnhem
 * Gebaseerd op "Ondersteuning in beeld" structuur
 */

import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

interface ZorgorganisatieData {
  naam: string
  beschrijving?: string
  type: 'GEMEENTE' | 'THUISZORG' | 'MANTELZORGSTEUNPUNT' | 'RESPIJTZORG' | 'DAGBESTEDING' | 'HUISARTS' | 'SOCIAAL_WIJKTEAM' | 'VRIJWILLIGERS' | 'OVERIG' | 'LANDELIJK'
  telefoon?: string
  email?: string
  website?: string
  gemeente: string
  onderdeelTest?: string
  soortHulp?: string
  dienst?: string
  doelgroep?: string
  kosten?: string
  zichtbaarBijLaag?: boolean
  zichtbaarBijGemiddeld?: boolean
  zichtbaarBijHoog?: boolean
}

// Nijmegen organisaties
const nijmegenOrganisaties: ZorgorganisatieData[] = [
  // Mantelzorgondersteuning
  {
    naam: 'Mantelzorg Nijmegen',
    beschrijving: 'Het eerste aanspreekpunt voor mantelzorgers. Tips, advies, steun en een luisterend oor. Speciale aandacht voor jonge, werkende en migranten mantelzorgers.',
    type: 'MANTELZORGSTEUNPUNT',
    telefoon: '024 254 157 12',
    email: 'Mantelzorg@sterker.nl',
    website: 'https://mantelzorg-nijmegen.nl',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Mantelzorgondersteuning',
    soortHulp: 'Informatie en advies',
    doelgroep: 'Alle mantelzorgers',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'Mantelzorg Nijmegen - Emotionele steun',
    beschrijving: 'Gespreksgroepen, wandelingen en bijeenkomsten waar je andere mantelzorgers ontmoet en ervaringen deelt.',
    type: 'MANTELZORGSTEUNPUNT',
    telefoon: '024 254 157 12',
    email: 'Mantelzorg@sterker.nl',
    website: 'https://mantelzorg-nijmegen.nl/mantelzorgers/',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Mantelzorgondersteuning',
    soortHulp: 'Emotionele steun',
    doelgroep: 'Alle mantelzorgers',
    kosten: 'Gratis',
    zichtbaarBijLaag: false,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'Mantelzorg Nijmegen - Cursussen',
    beschrijving: 'Cursussen en trainingen voor mantelzorgers over omgaan met zorg, grenzen stellen en zelfzorg.',
    type: 'MANTELZORGSTEUNPUNT',
    telefoon: '024 254 157 12',
    email: 'Mantelzorg@sterker.nl',
    website: 'https://mantelzorg-nijmegen.nl/mantelzorgers/',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Mantelzorgondersteuning',
    soortHulp: 'Educatie',
    doelgroep: 'Alle mantelzorgers',
    kosten: 'Gratis',
    zichtbaarBijLaag: false,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'ZZG Zorggroep - Mantelzorg',
    beschrijving: 'Informatie en hulp bij mantelzorg. Ondersteuning voor wie zorgt voor partner, ouder, buur of vriend.',
    type: 'THUISZORG',
    website: 'https://www.zzgzorggroep.nl/mantelzorg/',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Mantelzorgondersteuning',
    soortHulp: 'Informatie en advies',
    doelgroep: 'Alle mantelzorgers',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'ZorgMies Nijmegen',
    beschrijving: 'Hulp bij boodschappen, maaltijden, licht huishoudelijk werk en persoonlijke verzorging. Ontlast mantelzorgers.',
    type: 'THUISZORG',
    website: 'https://zorgmies.nl/zorgmies-nijmegen/',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Mantelzorgondersteuning',
    soortHulp: 'Vervangende mantelzorg',
    doelgroep: 'Mantelzorgers die ontlasting nodig hebben',
    zichtbaarBijLaag: false,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'VraagHulp Nijmegen',
    beschrijving: 'Onafhankelijk informatiepunt voor mantelzorgers met vragen over zorg en ondersteuning.',
    type: 'GEMEENTE',
    website: 'https://www.vraaghulpnijmegen.nl/wie-helpt/ik-ben-mantelzorger-en-heb-een-vraag/',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Mantelzorgondersteuning',
    soortHulp: 'Informatie en advies',
    doelgroep: 'Alle mantelzorgers',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'Gemeente Nijmegen - Mantelzorgcompliment',
    beschrijving: 'Waardering voor mantelzorgers in de vorm van een jaarlijks compliment van de gemeente.',
    type: 'GEMEENTE',
    website: 'https://www.nijmegen.nl/diensten/zorg-en-hulp/mantelzorgcompliment/',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Mantelzorgondersteuning',
    soortHulp: 'Financiele regelingen',
    doelgroep: 'Alle mantelzorgers',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'Gemeente Nijmegen - Hulp huishouden mantelzorgers',
    beschrijving: 'Tijdelijke huishoudelijke hulp voor mantelzorgers die overbelast zijn.',
    type: 'GEMEENTE',
    website: 'https://www.nijmegen.nl/diensten/zorg-en-hulp/hulp-huishouden-mantelzorgers/',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Huishoudelijke taken',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Overbelaste mantelzorgers',
    zichtbaarBijLaag: false,
    zichtbaarBijGemiddeld: false,
    zichtbaarBijHoog: true,
  },
  // Hulp bij taken
  {
    naam: 'Sterker Sociaal Werk Nijmegen',
    beschrijving: 'Breed sociaal werk met ondersteuning voor mantelzorgers bij diverse zorgtaken en hulpvragen.',
    type: 'SOCIAAL_WIJKTEAM',
    website: 'https://www.sterker.nl/diensten/mantelzorg',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Administratie en aanvragen',
    soortHulp: 'Informatie en advies',
    doelgroep: 'Alle inwoners',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'Buurtteams Nijmegen',
    beschrijving: 'Eerste aanspreekpunt voor hulpvragen. Onderzoekt welke hulp nodig is en verwijst door.',
    type: 'SOCIAAL_WIJKTEAM',
    website: 'https://www.nijmegen.nl',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Plannen en organiseren',
    soortHulp: 'Informatie en advies',
    doelgroep: 'Alle inwoners',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  // ==========================================
  // HULP BIJ TAKEN - NIJMEGEN
  // ==========================================
  // Boodschappen
  {
    naam: 'Hulpdienst Nijmegen - Boodschappen',
    beschrijving: 'Vrijwilligers helpen met boodschappen doen voor ouderen, zieken en mantelzorgers.',
    type: 'VRIJWILLIGERS',
    telefoon: '024-3228280',
    website: 'https://www.hulpdienstnijmegen.nl/',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Boodschappen',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Ouderen, zieken, mantelzorgers',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'ZorgMies Nijmegen - Boodschappen',
    beschrijving: 'Praktische hulp bij boodschappen doen. Betaald via PGB, zorgverzekeraar of particulier.',
    type: 'THUISZORG',
    website: 'https://zorgmies.nl/zorgmies-nijmegen/',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Boodschappen',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Ouderen en zorgvragers',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  // Huishoudelijke taken
  {
    naam: 'Gemeente Nijmegen - Huishoudelijke hulp WMO',
    beschrijving: 'Huishoudelijke hulp via de WMO. Aanvragen bij de gemeente. Eigen bijdrage €21/maand.',
    type: 'GEMEENTE',
    website: 'https://www.nijmegen.nl/diensten/zorg-en-hulp/huishoudelijke-hulp/',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Huishoudelijke taken',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Inwoners die zelf niet kunnen schoonmaken',
    kosten: '€21 per maand',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'Actief Zorg Nijmegen',
    beschrijving: 'Professionele huishoudelijke hulp zodat u langer thuis kunt wonen. Via WMO of particulier.',
    type: 'THUISZORG',
    website: 'https://www.actiefzorg.nl/thuiszorg/nijmegen/huishoudelijke-verzorging',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Huishoudelijke taken',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Ouderen en zorgvragers',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'Uw Zorgcompaan Nijmegen',
    beschrijving: 'Thuishulp inclusief verzorging, huishouden, boodschappen en uitjes. Ook 24-uurs zorg mogelijk.',
    type: 'THUISZORG',
    website: 'https://www.uwzorgcompaan.eu/thuishulp-nijmegen',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Huishoudelijke taken',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Ouderen en zorgvragers',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  // Klusjes
  {
    naam: 'Hulpdienst Nijmegen - Klusjes',
    beschrijving: 'Vrijwilligers helpen met kleine klusjes in huis, eenvoudig tuinonderhoud.',
    type: 'VRIJWILLIGERS',
    telefoon: '024-3228280',
    website: 'https://www.hulpdienstnijmegen.nl/',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Klusjes in en om het huis',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Ouderen, zieken, mantelzorgers',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  // Vervoer
  {
    naam: 'AutoMaatje Nijmegen',
    beschrijving: 'Vrijwillige chauffeurs brengen u naar afspraken. Samenwerking ANWB en Sterker Ouderenwerk.',
    type: 'VRIJWILLIGERS',
    website: 'https://sterkerouderenwerk.nl/en/diensten/anwb-automaatje/',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Vervoer',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Ouderen die niet zelf kunnen rijden',
    kosten: '€0,35 per km',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'Regiotaxi AVAN Nijmegen',
    beschrijving: 'Van deur tot deur vervoer in regio Arnhem-Nijmegen. Met WMO-indicatie of OV-pas.',
    type: 'GEMEENTE',
    website: 'https://www.avan-vervoer.nl/',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Vervoer',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Mensen die niet zelfstandig kunnen reizen',
    kosten: 'Laag tarief met indicatie',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'Hulpdienst Nijmegen - Vervoer',
    beschrijving: 'Vrijwilligers bieden vervoer en begeleiding naar ziekenhuis of andere afspraken.',
    type: 'VRIJWILLIGERS',
    telefoon: '024-3228280',
    website: 'https://www.hulpdienstnijmegen.nl/',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Vervoer',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Ouderen, zieken, mantelzorgers',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'ZorgMies Nijmegen - Begeleid vervoer',
    beschrijving: 'Begeleiding bij vervoer naar doktersafspraken of familiebezoek.',
    type: 'THUISZORG',
    website: 'https://zorgmies.nl/zorgmies-nijmegen/',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Vervoer',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Mensen die begeleiding nodig hebben',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  // Maaltijden
  {
    naam: 'Tafeltje Dekje Nijmegen',
    beschrijving: 'Warme maaltijden aan huis bezorgd. Diverse buurthuizen bieden maaltijdservice.',
    type: 'VRIJWILLIGERS',
    website: 'https://www.maaltijdvoorzieningen.nl/nijmegen/',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Bereiden en/of nuttigen van maaltijden',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Ouderen die niet zelf kunnen koken',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'Stichting Thuisgekookt Nijmegen',
    beschrijving: 'Buren koken voor buren. Verse maaltijden én sociaal contact.',
    type: 'VRIJWILLIGERS',
    website: 'https://thuisgekookt.nl/',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Bereiden en/of nuttigen van maaltijden',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Ouderen en mensen die behoefte hebben aan contact',
    kosten: 'Laag tarief',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  // Sociaal contact
  {
    naam: 'Hulpdienst Nijmegen - Bezoek',
    beschrijving: 'Vrijwilligers komen langs voor gezelschap, wandelen of een praatje.',
    type: 'VRIJWILLIGERS',
    telefoon: '024-3228280',
    website: 'https://www.hulpdienstnijmegen.nl/',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Sociaal contact en activiteiten',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Ouderen, zieken, eenzame mensen',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'Maatjes Nijmegen',
    beschrijving: 'Vrijwillige maatjes voor mensen die behoefte hebben aan contact en ondersteuning.',
    type: 'VRIJWILLIGERS',
    website: 'https://www.maatjesnijmegen.nl/',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Sociaal contact en activiteiten',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Mensen die behoefte hebben aan sociaal contact',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  // Administratie
  {
    naam: 'Hulpdienst Nijmegen - Administratie',
    beschrijving: 'Vrijwilligers helpen met eenvoudige administratieve taken en formulieren.',
    type: 'VRIJWILLIGERS',
    telefoon: '024-3228280',
    website: 'https://www.hulpdienstnijmegen.nl/',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Administratie en aanvragen',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Ouderen, zieken, mantelzorgers',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  // Persoonlijke verzorging
  {
    naam: 'ZZG Zorggroep Nijmegen - Thuiszorg',
    beschrijving: 'Professionele thuiszorg: persoonlijke verzorging, verpleging en begeleiding.',
    type: 'THUISZORG',
    website: 'https://www.zzgzorggroep.nl/zorg-thuis/',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Persoonlijke verzorging',
    soortHulp: 'Professionele zorg',
    doelgroep: 'Mensen met zorgbehoefte',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  // Dagbesteding / Respijtzorg
  {
    naam: 'Sterker Ouderenwerk - Deel de Dag',
    beschrijving: 'Dagbesteding voor senioren met gevarieerd programma. Gratis voor Nijmegse 65-plussers.',
    type: 'DAGBESTEDING',
    website: 'https://sterkerouderenwerk.nl/en/diensten/deel-de-dag-dagbesteding/',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Mantelzorgondersteuning',
    soortHulp: 'Respijtzorg',
    doelgroep: 'Senioren 65+ in Nijmegen',
    kosten: 'Gratis (subsidie gemeente)',
    zichtbaarBijLaag: false,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'OBG Dagbesteding Nijmegen',
    beschrijving: 'Dagbesteding voor mensen met lichte tot zwaardere zorgvraag. Via WMO of WLZ.',
    type: 'DAGBESTEDING',
    website: 'https://obg.nu/zorg-gezondheid/dagbesteding/',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Mantelzorgondersteuning',
    soortHulp: 'Respijtzorg',
    doelgroep: 'Mensen met zorgvraag',
    zichtbaarBijLaag: false,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'ZZG Zorggroep - Dagbehandeling',
    beschrijving: 'Dagbehandeling op locatie Maanvis in Hatert. Contact via Zorgbemiddeling ZZG.',
    type: 'DAGBESTEDING',
    website: 'https://www.zzgzorggroep.nl/zorg-thuis/dagbehandeling-op-locatie/',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Mantelzorgondersteuning',
    soortHulp: 'Respijtzorg',
    doelgroep: 'Mensen met zorgvraag',
    zichtbaarBijLaag: false,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  // Plannen en organiseren
  {
    naam: 'Sterker Sociaal Werk - Cliëntondersteuning',
    beschrijving: 'Hulp bij het regelen en organiseren van zorg. Onafhankelijke cliëntondersteuning.',
    type: 'SOCIAAL_WIJKTEAM',
    website: 'https://www.sterker.nl/',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Plannen en organiseren',
    soortHulp: 'Informatie en advies',
    doelgroep: 'Alle inwoners',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'MEE Gelderse Poort Nijmegen',
    beschrijving: 'Onafhankelijke cliëntondersteuning. Helpt bij het regelen van zorg en ondersteuning.',
    type: 'OVERIG',
    website: 'https://www.meegeldersepoort.nl/',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Plannen en organiseren',
    soortHulp: 'Informatie en advies',
    doelgroep: 'Mensen met een beperking of chronische ziekte',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  // Huisdieren
  {
    naam: 'Dierenambulance Nijmegen',
    beschrijving: 'Hulp bij vervoer van zieke of gewonde huisdieren. Noodopvang mogelijk.',
    type: 'VRIJWILLIGERS',
    telefoon: '024-3731594',
    website: 'https://www.dierenambulancenijmegen.nl/',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Huisdieren',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Huisdiereigenaren',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'Dierenvoedselbank Nijmegen',
    beschrijving: 'Gratis dierenvoer voor mensen met een laag inkomen.',
    type: 'VRIJWILLIGERS',
    website: 'https://www.dierenvoedselbanknederland.nl/',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Huisdieren',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Huisdiereigenaren met laag inkomen',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'Hulpdienst Nijmegen - Huisdieren uitlaten',
    beschrijving: 'Vrijwilligers helpen met het uitlaten van de hond als u dit zelf niet kunt.',
    type: 'VRIJWILLIGERS',
    telefoon: '024-3228280',
    website: 'https://www.hulpdienstnijmegen.nl/',
    gemeente: 'Nijmegen',
    onderdeelTest: 'Huisdieren',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Ouderen, zieken, mantelzorgers',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
]

// Arnhem organisaties
const arnhemOrganisaties: ZorgorganisatieData[] = [
  // Mantelzorgondersteuning
  {
    naam: 'MVT Arnhem - Mantelzorg en Vrijwillige Thuishulp',
    beschrijving: 'Ondersteuning voor alle mantelzorgers in Arnhem. Info, advies, luisterend oor, zorgadvies en vrijwillige hulp.',
    type: 'MANTELZORGSTEUNPUNT',
    website: 'https://www.mvtarnhem.nl/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Mantelzorgondersteuning',
    soortHulp: 'Informatie en advies',
    doelgroep: 'Alle mantelzorgers in Arnhem',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'MVT Arnhem - Emotionele ondersteuning',
    beschrijving: 'Luisterend oor, gespreksgroepen en activiteiten voor mantelzorgers die behoefte hebben aan steun.',
    type: 'MANTELZORGSTEUNPUNT',
    website: 'https://www.mvtarnhem.nl/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Mantelzorgondersteuning',
    soortHulp: 'Emotionele steun',
    doelgroep: 'Alle mantelzorgers',
    kosten: 'Gratis',
    zichtbaarBijLaag: false,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'MVT Arnhem - Training en voorlichting',
    beschrijving: 'Trainingen en workshops voor mantelzorgers over zelfzorg en omgaan met zorgsituaties.',
    type: 'MANTELZORGSTEUNPUNT',
    website: 'https://www.mvtarnhem.nl/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Mantelzorgondersteuning',
    soortHulp: 'Educatie',
    doelgroep: 'Alle mantelzorgers',
    kosten: 'Gratis',
    zichtbaarBijLaag: false,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'MVT Arnhem - Jonge mantelzorgers',
    beschrijving: 'Speciale ondersteuning voor jongeren die opgroeien met zorg voor een naaste.',
    type: 'MANTELZORGSTEUNPUNT',
    website: 'https://www.mvtarnhem.nl/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Mantelzorgondersteuning',
    soortHulp: 'Emotionele steun',
    doelgroep: 'Jonge mantelzorgers tot 24 jaar',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'MVT Arnhem - Werkende mantelzorgers',
    beschrijving: 'Ondersteuning voor mantelzorgers die werk en zorg combineren.',
    type: 'MANTELZORGSTEUNPUNT',
    website: 'https://www.mvtarnhem.nl/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Mantelzorgondersteuning',
    soortHulp: 'Informatie en advies',
    doelgroep: 'Werkende mantelzorgers',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'MVT Arnhem - Mantelzorg & Andere cultuur',
    beschrijving: 'Ondersteuning voor mantelzorgers met een migratie-achtergrond.',
    type: 'MANTELZORGSTEUNPUNT',
    website: 'https://www.mvtarnhem.nl/mantelzorg-en-cultuur',
    gemeente: 'Arnhem',
    onderdeelTest: 'Mantelzorgondersteuning',
    soortHulp: 'Emotionele steun',
    doelgroep: 'Mantelzorgers met migratie-achtergrond',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'MVT Arnhem - Dementie mantelzorgers',
    beschrijving: 'Speciale ondersteuning voor mantelzorgers die zorgen voor iemand met dementie.',
    type: 'MANTELZORGSTEUNPUNT',
    website: 'https://www.mvtarnhem.nl/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Mantelzorgondersteuning',
    soortHulp: 'Emotionele steun',
    doelgroep: 'Mantelzorgers van mensen met dementie',
    kosten: 'Gratis',
    zichtbaarBijLaag: false,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'Gemeente Arnhem - Mantelzorgcompliment',
    beschrijving: 'Waardering voor mantelzorgers via het mantelzorgcompliment. Aanvragen van 1 april t/m 31 december.',
    type: 'GEMEENTE',
    website: 'https://www.mvtarnhem.nl/mantelzorgcompliment',
    gemeente: 'Arnhem',
    onderdeelTest: 'Mantelzorgondersteuning',
    soortHulp: 'Financiele regelingen',
    doelgroep: 'Alle mantelzorgers in Arnhem',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'Adviespunt Zorgbelang Arnhem',
    beschrijving: 'Gratis onafhankelijke clientondersteuning. Hulp bij het vinden van passende zorg en ondersteuning.',
    type: 'OVERIG',
    website: 'https://www.mvtarnhem.nl/organisaties-in-arnhem/onafhankelijke-client-ondersteuning',
    gemeente: 'Arnhem',
    onderdeelTest: 'Mantelzorgondersteuning',
    soortHulp: 'Informatie en advies',
    doelgroep: 'Alle inwoners van Arnhem',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'Sociale Wijkteams Arnhem',
    beschrijving: 'Eerste aanspreekpunt voor hulp en ondersteuning in de wijk. Advies, begeleiding en doorverwijzing.',
    type: 'SOCIAAL_WIJKTEAM',
    website: 'https://www.arnhem.nl/alle-onderwerpen/zorg-en-welzijn/mantelzorgers-en-vrijwilligers/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Plannen en organiseren',
    soortHulp: 'Informatie en advies',
    doelgroep: 'Alle inwoners',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  // Hulp bij taken
  {
    naam: 'MVT Arnhem - Vrijwillige Thuishulp',
    beschrijving: 'Vrijwilligers helpen met tuinonderhoud en klusjes in huis. Ook voor mantelzorgers die tijd tekort komen.',
    type: 'VRIJWILLIGERS',
    website: 'https://www.mvtarnhem.nl/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Klusjes in en om het huis',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Mantelzorgers en zorgvragers',
    kosten: 'Gratis',
    zichtbaarBijLaag: false,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'Bijzonder in Arnhem - Mantelzorg',
    beschrijving: 'Overzicht van alle mantelzorg ondersteuning in Arnhem. Vindt hulp die bij jouw situatie past.',
    type: 'OVERIG',
    website: 'https://www.bijzonderinarnhem.nl/mantelzorg',
    gemeente: 'Arnhem',
    onderdeelTest: 'Mantelzorgondersteuning',
    soortHulp: 'Informatie en advies',
    doelgroep: 'Alle mantelzorgers',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'Arnhem Doet - Mantelzorg platform',
    beschrijving: 'Platform met informatie over mantelzorg ondersteuning in Arnhem.',
    type: 'OVERIG',
    website: 'https://arnhemdoet.nl/thema-s/mantelzorg/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Mantelzorgondersteuning',
    soortHulp: 'Informatie en advies',
    doelgroep: 'Alle mantelzorgers',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  // ==========================================
  // HULP BIJ TAKEN - ARNHEM
  // ==========================================
  // Boodschappen
  {
    naam: 'MVT Arnhem - Boodschappen hulp',
    beschrijving: 'Vrijwilligers helpen met boodschappen doen voor een korte periode. €5 per klus.',
    type: 'VRIJWILLIGERS',
    telefoon: '026-3703540',
    website: 'https://www.mvtarnhem.nl/thuishulp',
    gemeente: 'Arnhem',
    onderdeelTest: 'Boodschappen',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Ouderen, zieken, mantelzorgers',
    kosten: '€5 per klus',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'ZorgMies Arnhem - Boodschappen',
    beschrijving: 'Praktische hulp bij boodschappen. Aanvullende mantelzorg op maat.',
    type: 'THUISZORG',
    website: 'https://zorgmies.nl/zorgmies-arnhem/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Boodschappen',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Ouderen en zorgvragers',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'VoorElkaarInArnhem - Boodschappen',
    beschrijving: 'Hulp bij boodschappen doen als je dit tijdelijk niet zelf kunt.',
    type: 'VRIJWILLIGERS',
    website: 'https://www.voorelkaarinarnhem.nl/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Boodschappen',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Inwoners die hulp nodig hebben',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  // Huishoudelijke taken
  {
    naam: 'Pleyade Arnhem - Huishoudelijke hulp',
    beschrijving: 'Professionele huishoudelijke hulp voor ouderen. Via gemeente Arnhem (WMO).',
    type: 'THUISZORG',
    website: 'https://pleyade.nl/zorg/thuis/6/huishoudelijke-hulp',
    gemeente: 'Arnhem',
    onderdeelTest: 'Huishoudelijke taken',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Ouderen in wijken rond Pleyade locaties',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'Actief Zorg Arnhem',
    beschrijving: 'Huishoudelijke hulp zodat u langer thuis kunt wonen. Via WMO of particulier.',
    type: 'THUISZORG',
    website: 'https://www.actiefzorg.nl/thuiszorg/arnhem/huishoudelijke-verzorging',
    gemeente: 'Arnhem',
    onderdeelTest: 'Huishoudelijke taken',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Ouderen en zorgvragers',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'VoorElkaarInArnhem - Huishouden',
    beschrijving: 'Hulp bij schoonmaken en opruimen als je dit tijdelijk niet zelf kunt.',
    type: 'VRIJWILLIGERS',
    website: 'https://www.voorelkaarinarnhem.nl/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Huishoudelijke taken',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Inwoners die hulp nodig hebben',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  // Klusjes
  {
    naam: 'MVT Arnhem - Kleine klusjes',
    beschrijving: 'Vrijwilligers helpen met kleine klusjes: lamp ophangen, fotolijst, etc. €5 per klus.',
    type: 'VRIJWILLIGERS',
    telefoon: '026-3703540',
    website: 'https://www.mvtarnhem.nl/thuishulp',
    gemeente: 'Arnhem',
    onderdeelTest: 'Klusjes in en om het huis',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Ouderen, zieken, mantelzorgers',
    kosten: '€5 per klus',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'MVT Arnhem - Tuinwerk',
    beschrijving: 'Vrijwilligers helpen met tuinonderhoud. Jaarlijkse tuindoedag in juni.',
    type: 'VRIJWILLIGERS',
    telefoon: '026-3703540',
    website: 'https://www.mvtarnhem.nl/thuishulp',
    gemeente: 'Arnhem',
    onderdeelTest: 'Klusjes in en om het huis',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Ouderen, zieken, mantelzorgers',
    kosten: '€5 per klus',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'VoorElkaarInArnhem - Klusjes',
    beschrijving: 'Hulp bij kleine klusjes: plankje ophangen, wasmachine aansluiten, etc.',
    type: 'VRIJWILLIGERS',
    website: 'https://www.voorelkaarinarnhem.nl/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Klusjes in en om het huis',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Inwoners die hulp nodig hebben',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  // Vervoer
  {
    naam: 'Regiotaxi AVAN Arnhem',
    beschrijving: 'Van deur tot deur vervoer in regio Arnhem-Nijmegen. Met WMO-indicatie of OV-pas.',
    type: 'GEMEENTE',
    website: 'https://www.avan-vervoer.nl/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Vervoer',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Mensen die niet zelfstandig kunnen reizen',
    kosten: 'Laag tarief met indicatie',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'AutoMaatje Arnhem',
    beschrijving: 'Vrijwillige chauffeurs brengen ouderen naar afspraken. Via SWOA.',
    type: 'VRIJWILLIGERS',
    website: 'https://arnhemdoet.nl/hulp-en-ondersteuning/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Vervoer',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Ouderen die niet zelf kunnen rijden',
    kosten: '€0,35 per km',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'SWOA PlusBus Arnhem',
    beschrijving: 'Vervoer naar activiteiten en uitjes voor ouderen. Gevarieerd programma.',
    type: 'VRIJWILLIGERS',
    website: 'https://arnhemdoet.nl/hulp-en-ondersteuning/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Vervoer',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Ouderen 55+',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'ZorgMies Arnhem - Begeleid vervoer',
    beschrijving: 'Begeleiding bij vervoer naar doktersafspraken, familiebezoek of uitjes.',
    type: 'THUISZORG',
    website: 'https://zorgmies.nl/zorgmies-arnhem/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Vervoer',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Mensen die begeleiding nodig hebben',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  // Maaltijden
  {
    naam: 'Maaltijdservice Arnhem',
    beschrijving: 'Warme maaltijden aan huis bezorgd voor ouderen en mensen met beperkingen.',
    type: 'OVERIG',
    website: 'https://www.maaltijdvoorzieningen.nl/arnhem/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Bereiden en/of nuttigen van maaltijden',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Ouderen die niet zelf kunnen koken',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'VoorElkaarInArnhem - Maaltijden',
    beschrijving: 'Hulp bij maaltijd bereiden als je dit tijdelijk niet zelf kunt.',
    type: 'VRIJWILLIGERS',
    website: 'https://www.voorelkaarinarnhem.nl/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Bereiden en/of nuttigen van maaltijden',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Inwoners die hulp nodig hebben',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'ZorgMies Arnhem - Maaltijden',
    beschrijving: 'Hulp bij maaltijden bereiden en gezelschap tijdens het eten.',
    type: 'THUISZORG',
    website: 'https://zorgmies.nl/zorgmies-arnhem/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Bereiden en/of nuttigen van maaltijden',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Ouderen en zorgvragers',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  // Sociaal contact
  {
    naam: 'Suz&So Arnhem',
    beschrijving: 'Activiteitencentrum met dagbesteding. Verbindt kwetsbare burgers, jongeren en ouderen.',
    type: 'DAGBESTEDING',
    website: 'https://suzenso.nl/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Sociaal contact en activiteiten',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Kwetsbare burgers, ouderen',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'SWOA Arnhem - Activiteiten',
    beschrijving: 'Stichting Welzijn Ouderen Arnhem. Activiteiten en ondersteuning voor 55-plussers.',
    type: 'VRIJWILLIGERS',
    website: 'https://arnhemdoet.nl/hulp-en-ondersteuning/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Sociaal contact en activiteiten',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Ouderen 55+',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  // Administratie
  {
    naam: 'MVT Arnhem - Computerhulp',
    beschrijving: 'Vrijwilligers helpen met computer, software en modem installeren. €5 per klus.',
    type: 'VRIJWILLIGERS',
    telefoon: '026-3703540',
    website: 'https://www.mvtarnhem.nl/thuishulp',
    gemeente: 'Arnhem',
    onderdeelTest: 'Administratie en aanvragen',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Ouderen, zieken, mantelzorgers',
    kosten: '€5 per klus',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  // Persoonlijke verzorging
  {
    naam: 'ZorgMies Arnhem - Persoonlijke verzorging',
    beschrijving: 'Hulp bij persoonlijke verzorging en licht huishoudelijk werk. Ontlast mantelzorgers.',
    type: 'THUISZORG',
    website: 'https://zorgmies.nl/zorgmies-arnhem/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Persoonlijke verzorging',
    soortHulp: 'Professionele zorg',
    doelgroep: 'Ouderen en zorgvragers',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  // Dagbesteding / Respijtzorg
  {
    naam: 'DrieGasthuizenGroep - De Bonte Specht',
    beschrijving: 'Dagbesteding voor ouderen met beginnende dementie of lichamelijke klachten.',
    type: 'DAGBESTEDING',
    website: 'https://www.driegasthuizengroep.nl/zorg/dagbesteding/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Mantelzorgondersteuning',
    soortHulp: 'Respijtzorg',
    doelgroep: 'Ouderen met beginnende dementie',
    zichtbaarBijLaag: false,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'Insula Dei Huize Kohlmann - Logeeropvang',
    beschrijving: 'Respijtzorg in de vorm van logeren. Max 2 dagen per week of tijdens vakanties.',
    type: 'RESPIJTZORG',
    website: 'https://www.insuladei.nl/zorg/tijdelijk-verblijf-en-logeren/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Mantelzorgondersteuning',
    soortHulp: 'Respijtzorg',
    doelgroep: 'Mensen met WLZ-indicatie, mantelzorgers',
    kosten: 'Via WLZ of WMO',
    zichtbaarBijLaag: false,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'Derman Zorg Arnhem - Dagbesteding',
    beschrijving: 'Dagbesteding en woonzorg. Ontmoetingsplek met activiteiten en creativiteit.',
    type: 'DAGBESTEDING',
    website: 'https://dermanzorg.com/zorgaanbod/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Mantelzorgondersteuning',
    soortHulp: 'Respijtzorg',
    doelgroep: 'Mensen met dementie, ziekte of ouderdom',
    zichtbaarBijLaag: false,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'Netwerk Dementie Arnhem - Respijtzorg',
    beschrijving: 'Informatie over respijtzorg: dagopvang, logeeropvang en professionele begeleiding thuis.',
    type: 'OVERIG',
    website: 'https://www.netwerkdementiearnhemeo.nl/aanbod-per-gemeente/gemeente-arnhem/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Mantelzorgondersteuning',
    soortHulp: 'Respijtzorg',
    doelgroep: 'Mantelzorgers van mensen met dementie',
    kosten: 'Via WMO, WLZ of zorgverzekeraar',
    zichtbaarBijLaag: false,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  // Plannen en organiseren
  {
    naam: 'Wijkteams Arnhem - Cliëntondersteuning',
    beschrijving: 'Hulp bij het regelen en organiseren van zorg. Onafhankelijke cliëntondersteuning.',
    type: 'SOCIAAL_WIJKTEAM',
    website: 'https://www.wijkteamsarnhem.nl/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Plannen en organiseren',
    soortHulp: 'Informatie en advies',
    doelgroep: 'Alle inwoners',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'MEE Gelderse Poort Arnhem',
    beschrijving: 'Onafhankelijke cliëntondersteuning. Helpt bij het regelen van zorg en ondersteuning.',
    type: 'OVERIG',
    website: 'https://www.meegeldersepoort.nl/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Plannen en organiseren',
    soortHulp: 'Informatie en advies',
    doelgroep: 'Mensen met een beperking of chronische ziekte',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  // Huisdieren
  {
    naam: 'Dierenambulance Arnhem',
    beschrijving: 'Hulp bij vervoer van zieke of gewonde huisdieren. 24 uur bereikbaar.',
    type: 'VRIJWILLIGERS',
    telefoon: '0900-0245',
    website: 'https://www.dierenambulance-arnhem.nl/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Huisdieren',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Huisdiereigenaren',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'Dierenvoedselbank Arnhem',
    beschrijving: 'Gratis dierenvoer voor mensen met een laag inkomen.',
    type: 'VRIJWILLIGERS',
    website: 'https://www.dierenvoedselbanknederland.nl/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Huisdieren',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Huisdiereigenaren met laag inkomen',
    kosten: 'Gratis',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
  {
    naam: 'Dierenasiel Arnhem',
    beschrijving: 'Tijdelijke opvang voor huisdieren wanneer de eigenaar zelf niet kan zorgen.',
    type: 'VRIJWILLIGERS',
    telefoon: '026-4421471',
    website: 'https://www.dierenasielarnhem.nl/',
    gemeente: 'Arnhem',
    onderdeelTest: 'Huisdieren',
    soortHulp: 'Praktische hulp',
    doelgroep: 'Huisdiereigenaren',
    zichtbaarBijLaag: true,
    zichtbaarBijGemiddeld: true,
    zichtbaarBijHoog: true,
  },
]

async function seedNijmegenArnhem() {
  console.log('Seeding Nijmegen en Arnhem zorgorganisaties...\n')

  const allOrganisaties = [...nijmegenOrganisaties, ...arnhemOrganisaties]
  let created = 0
  let updated = 0
  let errors = 0

  for (const org of allOrganisaties) {
    try {
      // Check of organisatie al bestaat (op basis van naam en gemeente)
      const existing = await prisma.zorgorganisatie.findFirst({
        where: {
          naam: org.naam,
          gemeente: org.gemeente,
        },
      })

      if (existing) {
        // Update bestaande
        await prisma.zorgorganisatie.update({
          where: { id: existing.id },
          data: {
            beschrijving: org.beschrijving,
            type: org.type,
            telefoon: org.telefoon,
            email: org.email,
            website: org.website,
            onderdeelTest: org.onderdeelTest,
            soortHulp: org.soortHulp,
            dienst: org.dienst,
            doelgroep: org.doelgroep,
            kosten: org.kosten,
            zichtbaarBijLaag: org.zichtbaarBijLaag ?? false,
            zichtbaarBijGemiddeld: org.zichtbaarBijGemiddeld ?? false,
            zichtbaarBijHoog: org.zichtbaarBijHoog ?? true,
            isActief: true,
          },
        })
        console.log(`   Updated: ${org.naam}`)
        updated++
      } else {
        // Maak nieuwe aan
        await prisma.zorgorganisatie.create({
          data: {
            naam: org.naam,
            beschrijving: org.beschrijving,
            type: org.type,
            telefoon: org.telefoon,
            email: org.email,
            website: org.website,
            gemeente: org.gemeente,
            onderdeelTest: org.onderdeelTest,
            soortHulp: org.soortHulp,
            dienst: org.dienst,
            doelgroep: org.doelgroep,
            kosten: org.kosten,
            zichtbaarBijLaag: org.zichtbaarBijLaag ?? false,
            zichtbaarBijGemiddeld: org.zichtbaarBijGemiddeld ?? false,
            zichtbaarBijHoog: org.zichtbaarBijHoog ?? true,
            isActief: true,
          },
        })
        console.log(`   Created: ${org.naam}`)
        created++
      }
    } catch (error) {
      console.error(`   Error: ${org.naam}`, error)
      errors++
    }
  }

  console.log('\n' + '='.repeat(50))
  console.log('SAMENVATTING:')
  console.log(`   Nieuw: ${created}`)
  console.log(`   Bijgewerkt: ${updated}`)
  console.log(`   Fouten: ${errors}`)

  // Toon statistieken per gemeente
  const statsNijmegen = await prisma.zorgorganisatie.count({
    where: { gemeente: 'Nijmegen', isActief: true },
  })
  const statsArnhem = await prisma.zorgorganisatie.count({
    where: { gemeente: 'Arnhem', isActief: true },
  })

  console.log('\nPer gemeente:')
  console.log(`   Nijmegen: ${statsNijmegen} organisaties`)
  console.log(`   Arnhem: ${statsArnhem} organisaties`)
  console.log('='.repeat(50))

  await prisma.$disconnect()
}

// Run seed
seedNijmegenArnhem()
  .then(() => {
    console.log('\nSeed voltooid!')
    process.exit(0)
  })
  .catch((error) => {
    console.error('\nSeed gefaald:', error)
    process.exit(1)
  })
